name: Backend Image

on:
  push:
    branches: ["main"]
    # 메인 브랜치에 변경이 생기면 이미지 빌드/배포 실행
  workflow_dispatch: {}

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    if: ${{ github.actor != 'github-actions[bot]' }}
    # GitHub Actions 봇이 만든 커밋에 의해 재실행되는 루프 방지
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        # 전체 히스토리 체크아웃 (태그 기록 저장용)

      - name: Determine project layout
        id: layout
        shell: bash
        run: |
          if [ -f backend/gradlew ]; then
            echo "project_dir=backend" >> "$GITHUB_OUTPUT"
            echo "image_suffix=-backend" >> "$GITHUB_OUTPUT"
          else
            echo "project_dir=." >> "$GITHUB_OUTPUT"
            echo "image_suffix=" >> "$GITHUB_OUTPUT"
          fi
        # backend 폴더 유무에 따라 경로/이미지 접미사 결정

      - name: Compute image metadata
        id: vars
        shell: bash
        run: |
          OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO_LC=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          SUFFIX="${{ steps.layout.outputs.image_suffix }}"
          IMAGE="ghcr.io/${OWNER_LC}/${REPO_LC}${SUFFIX}"
          TAG="${GITHUB_SHA}"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "Resolved IMAGE=$IMAGE, TAG=$TAG"
        # GHCR 이미지 이름과 태그(SHA)를 계산해 환경 변수로 노출

      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle
        # 빌드/테스트용 JDK 21 설치 및 Gradle 캐시 사용

      - name: Run tests
        run: ./gradlew test --no-daemon
        working-directory: ${{ steps.layout.outputs.project_dir }}
        # 단위 테스트 실행으로 빌드 이전 검증

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        # GHCR 레지스트리에 로그인

      - name: Build and push image
        shell: bash
        working-directory: ${{ steps.layout.outputs.project_dir }}
        run: |
          docker build -t "$IMAGE:$TAG" -t "$IMAGE:latest" .
          docker push "$IMAGE:$TAG"
          docker push "$IMAGE:latest"
        # Docker 이미지 빌드 후 SHA/최신 태그로 푸시

      - name: Persist image tag
        shell: bash
        run: |
          TARGET_DIR="${{ steps.layout.outputs.project_dir }}"
          if [ "$TARGET_DIR" = "." ]; then
            TARGET_FILE="image-tag.txt"
          else
            TARGET_FILE="$TARGET_DIR/image-tag.txt"
          fi
          echo "$TAG" > "$TARGET_FILE"
          git add "$TARGET_FILE"
          if git diff --cached --quiet -- "$TARGET_FILE"; then
            echo "Image tag unchanged; skipping commit update."
            exit 0
          fi
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -m "chore(backend): update image tag $TAG"
          git push
        # 사용한 태그를 저장 파일에 기록하고 변경 시 커밋/푸시
